services:
  - type: web
    name: finance-rag-backend
    env: python
    region: singapore
    buildCommand: pip install -r backend_requirements.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: NUM_RESULTS
        sync: false
